# Generated by Django 3.2.4 on 2021-06-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название заметки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание заметки')),
                ('remind', models.DateTimeField(verbose_name='Время напоминания')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
